/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as SCodeRouteImport } from './routes/s/$code'
import { Route as OnboardingSelectPlanRouteImport } from './routes/onboarding/select-plan'
import { Route as OnboardingSelectCategoryRouteImport } from './routes/onboarding/select-category'
import { Route as OnboardingProTrialRouteImport } from './routes/onboarding/pro-trial'
import { Route as DashboardQrCodeRouteImport } from './routes/dashboard/qr-code'
import { Route as DashboardPollsRouteImport } from './routes/dashboard/polls'
import { Route as DashboardLinkShortenerRouteImport } from './routes/dashboard/link-shortener'
import { Route as DashboardInsightsRouteImport } from './routes/dashboard/insights'
import { Route as DashboardDesignRouteImport } from './routes/dashboard/design'
import { Route as DashboardAnonymousMessagesRouteImport } from './routes/dashboard/anonymous-messages'
import { Route as DashboardAccountRouteImport } from './routes/dashboard/account'
import { Route as AuthUsernameRouteImport } from './routes/auth/username'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthOtpRouteImport } from './routes/auth/otp'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AnonUsernameRouteImport } from './routes/anon/$username'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const SCodeRoute = SCodeRouteImport.update({
  id: '/s/$code',
  path: '/s/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingSelectPlanRoute = OnboardingSelectPlanRouteImport.update({
  id: '/onboarding/select-plan',
  path: '/onboarding/select-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingSelectCategoryRoute =
  OnboardingSelectCategoryRouteImport.update({
    id: '/onboarding/select-category',
    path: '/onboarding/select-category',
    getParentRoute: () => rootRouteImport,
  } as any)
const OnboardingProTrialRoute = OnboardingProTrialRouteImport.update({
  id: '/onboarding/pro-trial',
  path: '/onboarding/pro-trial',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardQrCodeRoute = DashboardQrCodeRouteImport.update({
  id: '/qr-code',
  path: '/qr-code',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPollsRoute = DashboardPollsRouteImport.update({
  id: '/polls',
  path: '/polls',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLinkShortenerRoute = DashboardLinkShortenerRouteImport.update({
  id: '/link-shortener',
  path: '/link-shortener',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInsightsRoute = DashboardInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDesignRoute = DashboardDesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnonymousMessagesRoute =
  DashboardAnonymousMessagesRouteImport.update({
    id: '/anonymous-messages',
    path: '/anonymous-messages',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardAccountRoute = DashboardAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthUsernameRoute = AuthUsernameRouteImport.update({
  id: '/auth/username',
  path: '/auth/username',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthOtpRoute = AuthOtpRouteImport.update({
  id: '/auth/otp',
  path: '/auth/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AnonUsernameRoute = AnonUsernameRouteImport.update({
  id: '/anon/$username',
  path: '/anon/$username',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/anon/$username': typeof AnonUsernameRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/otp': typeof AuthOtpRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/username': typeof AuthUsernameRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/anonymous-messages': typeof DashboardAnonymousMessagesRoute
  '/dashboard/design': typeof DashboardDesignRoute
  '/dashboard/insights': typeof DashboardInsightsRoute
  '/dashboard/link-shortener': typeof DashboardLinkShortenerRoute
  '/dashboard/polls': typeof DashboardPollsRoute
  '/dashboard/qr-code': typeof DashboardQrCodeRoute
  '/onboarding/pro-trial': typeof OnboardingProTrialRoute
  '/onboarding/select-category': typeof OnboardingSelectCategoryRoute
  '/onboarding/select-plan': typeof OnboardingSelectPlanRoute
  '/s/$code': typeof SCodeRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/anon/$username': typeof AnonUsernameRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/otp': typeof AuthOtpRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/username': typeof AuthUsernameRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/anonymous-messages': typeof DashboardAnonymousMessagesRoute
  '/dashboard/design': typeof DashboardDesignRoute
  '/dashboard/insights': typeof DashboardInsightsRoute
  '/dashboard/link-shortener': typeof DashboardLinkShortenerRoute
  '/dashboard/polls': typeof DashboardPollsRoute
  '/dashboard/qr-code': typeof DashboardQrCodeRoute
  '/onboarding/pro-trial': typeof OnboardingProTrialRoute
  '/onboarding/select-category': typeof OnboardingSelectCategoryRoute
  '/onboarding/select-plan': typeof OnboardingSelectPlanRoute
  '/s/$code': typeof SCodeRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/anon/$username': typeof AnonUsernameRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/otp': typeof AuthOtpRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/username': typeof AuthUsernameRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/anonymous-messages': typeof DashboardAnonymousMessagesRoute
  '/dashboard/design': typeof DashboardDesignRoute
  '/dashboard/insights': typeof DashboardInsightsRoute
  '/dashboard/link-shortener': typeof DashboardLinkShortenerRoute
  '/dashboard/polls': typeof DashboardPollsRoute
  '/dashboard/qr-code': typeof DashboardQrCodeRoute
  '/onboarding/pro-trial': typeof OnboardingProTrialRoute
  '/onboarding/select-category': typeof OnboardingSelectCategoryRoute
  '/onboarding/select-plan': typeof OnboardingSelectPlanRoute
  '/s/$code': typeof SCodeRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/dashboard'
    | '/anon/$username'
    | '/auth/login'
    | '/auth/otp'
    | '/auth/register'
    | '/auth/username'
    | '/dashboard/account'
    | '/dashboard/anonymous-messages'
    | '/dashboard/design'
    | '/dashboard/insights'
    | '/dashboard/link-shortener'
    | '/dashboard/polls'
    | '/dashboard/qr-code'
    | '/onboarding/pro-trial'
    | '/onboarding/select-category'
    | '/onboarding/select-plan'
    | '/s/$code'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/anon/$username'
    | '/auth/login'
    | '/auth/otp'
    | '/auth/register'
    | '/auth/username'
    | '/dashboard/account'
    | '/dashboard/anonymous-messages'
    | '/dashboard/design'
    | '/dashboard/insights'
    | '/dashboard/link-shortener'
    | '/dashboard/polls'
    | '/dashboard/qr-code'
    | '/onboarding/pro-trial'
    | '/onboarding/select-category'
    | '/onboarding/select-plan'
    | '/s/$code'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/dashboard'
    | '/anon/$username'
    | '/auth/login'
    | '/auth/otp'
    | '/auth/register'
    | '/auth/username'
    | '/dashboard/account'
    | '/dashboard/anonymous-messages'
    | '/dashboard/design'
    | '/dashboard/insights'
    | '/dashboard/link-shortener'
    | '/dashboard/polls'
    | '/dashboard/qr-code'
    | '/onboarding/pro-trial'
    | '/onboarding/select-category'
    | '/onboarding/select-plan'
    | '/s/$code'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  AnonUsernameRoute: typeof AnonUsernameRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthOtpRoute: typeof AuthOtpRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthUsernameRoute: typeof AuthUsernameRoute
  OnboardingProTrialRoute: typeof OnboardingProTrialRoute
  OnboardingSelectCategoryRoute: typeof OnboardingSelectCategoryRoute
  OnboardingSelectPlanRoute: typeof OnboardingSelectPlanRoute
  SCodeRoute: typeof SCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/s/$code': {
      id: '/s/$code'
      path: '/s/$code'
      fullPath: '/s/$code'
      preLoaderRoute: typeof SCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/select-plan': {
      id: '/onboarding/select-plan'
      path: '/onboarding/select-plan'
      fullPath: '/onboarding/select-plan'
      preLoaderRoute: typeof OnboardingSelectPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/select-category': {
      id: '/onboarding/select-category'
      path: '/onboarding/select-category'
      fullPath: '/onboarding/select-category'
      preLoaderRoute: typeof OnboardingSelectCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/pro-trial': {
      id: '/onboarding/pro-trial'
      path: '/onboarding/pro-trial'
      fullPath: '/onboarding/pro-trial'
      preLoaderRoute: typeof OnboardingProTrialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/qr-code': {
      id: '/dashboard/qr-code'
      path: '/qr-code'
      fullPath: '/dashboard/qr-code'
      preLoaderRoute: typeof DashboardQrCodeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/polls': {
      id: '/dashboard/polls'
      path: '/polls'
      fullPath: '/dashboard/polls'
      preLoaderRoute: typeof DashboardPollsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/link-shortener': {
      id: '/dashboard/link-shortener'
      path: '/link-shortener'
      fullPath: '/dashboard/link-shortener'
      preLoaderRoute: typeof DashboardLinkShortenerRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/insights': {
      id: '/dashboard/insights'
      path: '/insights'
      fullPath: '/dashboard/insights'
      preLoaderRoute: typeof DashboardInsightsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/design': {
      id: '/dashboard/design'
      path: '/design'
      fullPath: '/dashboard/design'
      preLoaderRoute: typeof DashboardDesignRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/anonymous-messages': {
      id: '/dashboard/anonymous-messages'
      path: '/anonymous-messages'
      fullPath: '/dashboard/anonymous-messages'
      preLoaderRoute: typeof DashboardAnonymousMessagesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/account': {
      id: '/dashboard/account'
      path: '/account'
      fullPath: '/dashboard/account'
      preLoaderRoute: typeof DashboardAccountRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/username': {
      id: '/auth/username'
      path: '/auth/username'
      fullPath: '/auth/username'
      preLoaderRoute: typeof AuthUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/otp': {
      id: '/auth/otp'
      path: '/auth/otp'
      fullPath: '/auth/otp'
      preLoaderRoute: typeof AuthOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anon/$username': {
      id: '/anon/$username'
      path: '/anon/$username'
      fullPath: '/anon/$username'
      preLoaderRoute: typeof AnonUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardAccountRoute: typeof DashboardAccountRoute
  DashboardAnonymousMessagesRoute: typeof DashboardAnonymousMessagesRoute
  DashboardDesignRoute: typeof DashboardDesignRoute
  DashboardInsightsRoute: typeof DashboardInsightsRoute
  DashboardLinkShortenerRoute: typeof DashboardLinkShortenerRoute
  DashboardPollsRoute: typeof DashboardPollsRoute
  DashboardQrCodeRoute: typeof DashboardQrCodeRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAccountRoute: DashboardAccountRoute,
  DashboardAnonymousMessagesRoute: DashboardAnonymousMessagesRoute,
  DashboardDesignRoute: DashboardDesignRoute,
  DashboardInsightsRoute: DashboardInsightsRoute,
  DashboardLinkShortenerRoute: DashboardLinkShortenerRoute,
  DashboardPollsRoute: DashboardPollsRoute,
  DashboardQrCodeRoute: DashboardQrCodeRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DashboardRoute: DashboardRouteWithChildren,
  AnonUsernameRoute: AnonUsernameRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthOtpRoute: AuthOtpRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthUsernameRoute: AuthUsernameRoute,
  OnboardingProTrialRoute: OnboardingProTrialRoute,
  OnboardingSelectCategoryRoute: OnboardingSelectCategoryRoute,
  OnboardingSelectPlanRoute: OnboardingSelectPlanRoute,
  SCodeRoute: SCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
